name: Main workflow
on: [push, pull_request]
jobs:
  run:
    name: Run
    runs-on: macos-latest
    env:
      CGO_ENABLED: '0'
      GO_EXTLINK_ENABLED: '0'
    strategy:
      matrix:
        go:
          - 1.12.x
          - 1.13.x
          - 1.14.x
          # TODO actions/setup-go#32
          #- latest
          #- tip
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Install Go
        uses: actions/setup-go@master
        with:
          go-version: ${{ matrix.go }}

      - name: Show Go version
        run: go version

      - name: Show Go environment
        run: go env

      - name: Run tests
        run: go test -v
