name: Tests
on: [push, pull_request]
jobs:
  run:
    name: Run
    runs-on: macos-latest
    env:
      CGO_ENABLED: '0'
      GO_EXTLINK_ENABLED: '0'
    strategy:
      fail-fast: false
      matrix:
        go:
          - 1.17.x
          - 1.18.x
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.0
      - name: Install Go
        uses: actions/setup-go@v3.0.0
        with:
          go-version: ${{ matrix.go }}
      - name: Get Go cache paths
        id: go-env
        run: |
          echo "::set-output name=cache::$(go env GOCACHE)"
          echo "::set-output name=modcache::$(go env GOMODCACHE)"
      - name: Set up Go cache
        uses: actions/cache@v2.1.7
        with:
          key: test-${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: test-${{ runner.os }}-go-
          path: |
            ${{ steps.go-env.outputs.cache }}
            ${{ steps.go-env.outputs.modcache }}
      - name: Run all tests
        if: ${{ matrix.go != '1.17.x' }}
        run: go test all

      # Go 1.17 does not support workspaces so 'all' does not match any package.
      # We manually run tests for packages where 1.17 compatibility is critical.
      - name: Run all tests
        if: ${{ matrix.go == '1.17.x' }}
        run: cd darwin && go test ./...
